"""Add export history table for audit tracking

Revision ID: 20260618_0001
Revises: 20260611_0003
Create Date: 2026-06-18 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260618_0001'
down_revision = '20260611_0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'export_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.String(), nullable=False),
        sa.Column('exported_by_id', sa.Integer(), nullable=False),
        sa.Column('exported_by_email', sa.String(255), nullable=True),
        sa.Column('data_type', sa.String(50), nullable=False),
        sa.Column('export_format', sa.String(20), nullable=False),
        sa.Column('record_count', sa.Integer(), nullable=True, server_default='0'),
        sa.Column('file_name', sa.String(255), nullable=True),
        sa.Column('export_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_history_company_id', 'export_history', ['company_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_export_history_company_id', table_name='export_history')
    op.drop_table('export_history')
    # ### end Alembic commands ###
