const employeesData = [
  {
    id: 1,
    name: 'John Doe',
    department: 'Engineering',
    designation: 'Frontend Developer',
    status: 'Active',
    email: 'john@example.com',
  },
  {
    id: 2,
    name: 'Sarah Smith',
    department: 'HR',
    designation: 'HR Manager',
    status: 'Inactive',
    email: 'sarah@example.com',
  },
  {
    id: 3,
    name: 'Michael Johnson',
    department: 'Finance',
    designation: 'Accountant',
    status: 'Active',
    email: 'michael@example.com',
  },
  {
    id: 4,
    name: 'Emily Davis',
    department: 'Engineering',
    designation: 'Backend Developer',
    status: 'Active',
    email: 'emily@example.com',
  },
  {
    id: 5,
    name: 'David Wilson',
    department: 'Marketing',
    designation: 'Marketing Specialist',
    status: 'Active',
    email: 'david@example.com',
  },
  {
    id: 6,
    name: 'Sophia Brown',
    department: 'Design',
    designation: 'UI/UX Designer',
    status: 'Inactive',
    email: 'sophia@example.com',
  },
  {
    id: 7,
    name: 'James Taylor',
    department: 'Engineering',
    designation: 'Full Stack Developer',
    status: 'Active',
    email: 'james@example.com',
  },
  {
    id: 8,
    name: 'Olivia Martinez',
    department: 'HR',
    designation: 'Recruiter',
    status: 'Active',
    email: 'olivia@example.com',
  },
  {
    id: 9,
    name: 'Daniel Anderson',
    department: 'Finance',
    designation: 'Financial Analyst',
    status: 'Inactive',
    email: 'daniel@example.com',
  },
  {
    id: 10,
    name: 'Emma Thomas',
    department: 'Engineering',
    designation: 'React Developer',
    status: 'Active',
    email: 'emma@example.com',
  },
  {
    id: 11,
    name: 'William Harris',
    department: 'Operations',
    designation: 'Operations Manager',
    status: 'Active',
    email: 'william@example.com',
  },
  {
    id: 12,
    name: 'Ava Clark',
    department: 'Design',
    designation: 'Graphic Designer',
    status: 'Inactive',
    email: 'ava@example.com',
  },
  {
    id: 13,
    name: 'Benjamin Lewis',
    department: 'Engineering',
    designation: 'DevOps Engineer',
    status: 'Active',
    email: 'benjamin@example.com',
  },
  {
    id: 14,
    name: 'Mia Walker',
    department: 'Marketing',
    designation: 'SEO Specialist',
    status: 'Active',
    email: 'mia@example.com',
  },
  {
    id: 15,
    name: 'Lucas Hall',
    department: 'Support',
    designation: 'Customer Support Executive',
    status: 'Inactive',
    email: 'lucas@example.com',
  },
  {
    id: 16,
    name: 'Charlotte Allen',
    department: 'Engineering',
    designation: 'Software Engineer',
    status: 'Active',
    email: 'charlotte@example.com',
  },
  {
    id: 17,
    name: 'Henry Young',
    department: 'Finance',
    designation: 'Payroll Manager',
    status: 'Active',
    email: 'henry@example.com',
  },
  {
    id: 18,
    name: 'Amelia King',
    department: 'Design',
    designation: 'Product Designer',
    status: 'Active',
    email: 'amelia@example.com',
  },
  {
    id: 19,
    name: 'Alexander Scott',
    department: 'Operations',
    designation: 'Team Lead',
    status: 'Inactive',
    email: 'alexander@example.com',
  },
  {
    id: 20,
    name: 'Harper Green',
    department: 'Engineering',
    designation: 'Mobile App Developer',
    status: 'Active',
    email: 'harper@example.com',
  },
]

export default employeesData